name: Crawl blocked domains and ips from Greatfire Analyzer
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00 UTC
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  aggregate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: ./go.mod

      - name: Test
        run: go test ./...

      - name: Run
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            go run ./ -outdir ./publish -parallel 10 -pages 200
          else
            go run ./ -outdir ./publish -parallel 10
          fi

      - name: Upload artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: publish
          path: ./publish/

      - name: Exclude invalid entries from published files
        if: github.event_name != 'pull_request'
        run: rm -f ./publish/invalid.txt

      - name: Set variables
        if: github.event_name != 'pull_request'
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Release and upload assets
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git push assets to "release" branch
        if: github.event_name != 'pull_request'
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add publish "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u publish release
